import thunk from 'redux-thunk';
import { rootSaga } from './saga';
import createSagaMiddleware from 'redux-saga';
import { applyMiddleware } from 'redux';
import { createStore } from 'redux';
import reducer from './redux';
const sagaMiddleware = createSagaMiddleware();
const store = createStore(reducer, applyMiddleware(thunk, sagaMiddleware));
sagaMiddleware.run(rootSaga);
export default store;
